ALTER TABLE upid ADD COLUMN ac_name_12 CHAR;
ALTER TABLE upid ADD COLUMN ac_reserved_12 CHAR;
ALTER TABLE upid ADD COLUMN booth_id_12 CHAR;
ALTER TABLE upid ADD COLUMN station_name_12 CHAR;
ALTER TABLE upid ADD COLUMN station_id_12 INTEGER;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
COMMIT;
