ALTER TABLE delhiid ADD COLUMN pc_id_09 INTEGER;
ALTER TABLE delhiid ADD COLUMN pc_name_09 CHAR;
ALTER TABLE delhiid ADD COLUMN pc_reserved_09 CHAR;
ALTER TABLE delhiid ADD COLUMN ac_name_14 CHAR;
ALTER TABLE delhiid ADD COLUMN ac_reserved_14 CHAR;
BEGIN TRANSACTION;
UPDATE delhiid SET ac_name_14 = 'Nerela' WHERE ac_id_09 = 1;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 1;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 1;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 1;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 1;
UPDATE delhiid SET ac_name_14 = 'Burari' WHERE ac_id_09 = 2;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 2;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 2;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 2;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 2;
UPDATE delhiid SET ac_name_14 = 'Timarpur' WHERE ac_id_09 = 3;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 3;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 3;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 3;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 3;
UPDATE delhiid SET ac_name_14 = 'Adarsh Nagar' WHERE ac_id_09 = 4;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 4;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 4;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 4;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 4;
UPDATE delhiid SET ac_name_14 = 'Badli' WHERE ac_id_09 = 5;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 5;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 5;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 5;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 5;
UPDATE delhiid SET ac_name_14 = 'Rithala' WHERE ac_id_09 = 6;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 6;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 6;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 6;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 6;
UPDATE delhiid SET ac_name_14 = 'Bawana' WHERE ac_id_09 = 7;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 7;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 7;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 7;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 7;
UPDATE delhiid SET ac_name_14 = 'Mundka' WHERE ac_id_09 = 8;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 8;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 8;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 8;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 8;
UPDATE delhiid SET ac_name_14 = 'Kirari' WHERE ac_id_09 = 9;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 9;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 9;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 9;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 9;
UPDATE delhiid SET ac_name_14 = 'Sultanpur majra' WHERE ac_id_09 = 10;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 10;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 10;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 10;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 10;
UPDATE delhiid SET ac_name_14 = 'Nangloi jat' WHERE ac_id_09 = 11;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 11;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 11;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 11;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 11;
UPDATE delhiid SET ac_name_14 = 'Mangol puri' WHERE ac_id_09 = 12;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 12;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 12;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 12;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 12;
UPDATE delhiid SET ac_name_14 = 'Rohini' WHERE ac_id_09 = 13;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 13;
UPDATE delhiid SET pc_id_09 = 5 WHERE ac_id_09 = 13;
UPDATE delhiid SET pc_name_09 = 'North West Delhi' WHERE ac_id_09 = 13;
UPDATE delhiid SET pc_reserved_09 = 'SC' WHERE ac_id_09 = 13;
UPDATE delhiid SET ac_name_14 = 'Shalimar bagh' WHERE ac_id_09 = 14;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 14;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 14;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 14;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 14;
UPDATE delhiid SET ac_name_14 = 'Shakur basti' WHERE ac_id_09 = 15;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 15;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 15;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 15;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 15;
UPDATE delhiid SET ac_name_14 = 'Tri Nagar' WHERE ac_id_09 = 16;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 16;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 16;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 16;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 16;
UPDATE delhiid SET ac_name_14 = 'Wazirpur' WHERE ac_id_09 = 17;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 17;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 17;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 17;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 17;
UPDATE delhiid SET ac_name_14 = 'Model town' WHERE ac_id_09 = 18;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 18;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 18;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 18;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 18;
UPDATE delhiid SET ac_name_14 = 'Sadar bazar' WHERE ac_id_09 = 19;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 19;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 19;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 19;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 19;
UPDATE delhiid SET ac_name_14 = 'Chandni chowk' WHERE ac_id_09 = 20;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 20;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 20;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 20;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 20;
UPDATE delhiid SET ac_name_14 = 'Matia mahal' WHERE ac_id_09 = 21;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 21;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 21;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 21;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 21;
UPDATE delhiid SET ac_name_14 = 'Ballimaran' WHERE ac_id_09 = 22;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 22;
UPDATE delhiid SET pc_id_09 = 1 WHERE ac_id_09 = 22;
UPDATE delhiid SET pc_name_09 = 'Chandni Chowk' WHERE ac_id_09 = 22;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 22;
UPDATE delhiid SET ac_name_14 = 'Karol bagh' WHERE ac_id_09 = 23;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 23;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 23;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 23;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 23;
UPDATE delhiid SET ac_name_14 = 'Patel Nagar' WHERE ac_id_09 = 24;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 24;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 24;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 24;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 24;
UPDATE delhiid SET ac_name_14 = 'Moti Nagar' WHERE ac_id_09 = 25;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 25;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 25;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 25;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 25;
UPDATE delhiid SET ac_name_14 = 'Madipur' WHERE ac_id_09 = 26;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 26;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 26;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 26;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 26;
UPDATE delhiid SET ac_name_14 = 'Rajouri garden' WHERE ac_id_09 = 27;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 27;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 27;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 27;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 27;
UPDATE delhiid SET ac_name_14 = 'Hari Nagar' WHERE ac_id_09 = 28;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 28;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 28;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 28;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 28;
UPDATE delhiid SET ac_name_14 = 'Tilak Nagar' WHERE ac_id_09 = 29;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 29;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 29;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 29;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 29;
UPDATE delhiid SET ac_name_14 = 'Janakpuri' WHERE ac_id_09 = 30;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 30;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 30;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 30;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 30;
UPDATE delhiid SET ac_name_14 = 'Vikaspuri' WHERE ac_id_09 = 31;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 31;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 31;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 31;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 31;
UPDATE delhiid SET ac_name_14 = 'Uttam Nagar' WHERE ac_id_09 = 32;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 32;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 32;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 32;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 32;
UPDATE delhiid SET ac_name_14 = 'Dwarka' WHERE ac_id_09 = 33;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 33;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 33;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 33;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 33;
UPDATE delhiid SET ac_name_14 = 'Matiala' WHERE ac_id_09 = 34;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 34;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 34;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 34;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 34;
UPDATE delhiid SET ac_name_14 = 'Najafgarh' WHERE ac_id_09 = 35;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 35;
UPDATE delhiid SET pc_id_09 = 6 WHERE ac_id_09 = 35;
UPDATE delhiid SET pc_name_09 = 'West Delhi' WHERE ac_id_09 = 35;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 35;
UPDATE delhiid SET ac_name_14 = 'Bijwasan' WHERE ac_id_09 = 36;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 36;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 36;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 36;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 36;
UPDATE delhiid SET ac_name_14 = 'Palam' WHERE ac_id_09 = 37;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 37;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 37;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 37;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 37;
UPDATE delhiid SET ac_name_14 = 'Delhi Cantt' WHERE ac_id_09 = 38;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 38;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 38;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 38;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 38;
UPDATE delhiid SET ac_name_14 = 'Rajinder Nagar' WHERE ac_id_09 = 39;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 39;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 39;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 39;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 39;
UPDATE delhiid SET ac_name_14 = 'New delhi' WHERE ac_id_09 = 40;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 40;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 40;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 40;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 40;
UPDATE delhiid SET ac_name_14 = 'Jangpura' WHERE ac_id_09 = 41;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 41;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 41;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 41;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 41;
UPDATE delhiid SET ac_name_14 = 'Kasturba Nagar' WHERE ac_id_09 = 42;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 42;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 42;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 42;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 42;
UPDATE delhiid SET ac_name_14 = 'Malviya Nagar' WHERE ac_id_09 = 43;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 43;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 43;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 43;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 43;
UPDATE delhiid SET ac_name_14 = 'R R k k Puram' WHERE ac_id_09 = 44;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 44;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 44;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 44;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 44;
UPDATE delhiid SET ac_name_14 = 'Mehrauli' WHERE ac_id_09 = 45;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 45;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 45;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 45;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 45;
UPDATE delhiid SET ac_name_14 = 'Chhatarpur' WHERE ac_id_09 = 46;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 46;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 46;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 46;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 46;
UPDATE delhiid SET ac_name_14 = 'Deoli' WHERE ac_id_09 = 47;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 47;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 47;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 47;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 47;
UPDATE delhiid SET ac_name_14 = 'Ambedkar Nagar' WHERE ac_id_09 = 48;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 48;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 48;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 48;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 48;
UPDATE delhiid SET ac_name_14 = 'Sangam vihar' WHERE ac_id_09 = 49;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 49;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 49;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 49;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 49;
UPDATE delhiid SET ac_name_14 = 'Greater kailash' WHERE ac_id_09 = 50;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 50;
UPDATE delhiid SET pc_id_09 = 4 WHERE ac_id_09 = 50;
UPDATE delhiid SET pc_name_09 = 'New Delhi' WHERE ac_id_09 = 50;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 50;
UPDATE delhiid SET ac_name_14 = 'Kalkaji' WHERE ac_id_09 = 51;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 51;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 51;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 51;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 51;
UPDATE delhiid SET ac_name_14 = 'Tughlakabad' WHERE ac_id_09 = 52;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 52;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 52;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 52;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 52;
UPDATE delhiid SET ac_name_14 = 'Badarpur' WHERE ac_id_09 = 53;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 53;
UPDATE delhiid SET pc_id_09 = 7 WHERE ac_id_09 = 53;
UPDATE delhiid SET pc_name_09 = 'South Delhi' WHERE ac_id_09 = 53;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 53;
UPDATE delhiid SET ac_name_14 = 'Okhla' WHERE ac_id_09 = 54;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 54;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 54;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 54;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 54;
UPDATE delhiid SET ac_name_14 = 'Trilokpuri' WHERE ac_id_09 = 55;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 55;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 55;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 55;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 55;
UPDATE delhiid SET ac_name_14 = 'Kondli' WHERE ac_id_09 = 56;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 56;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 56;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 56;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 56;
UPDATE delhiid SET ac_name_14 = 'Patparganj' WHERE ac_id_09 = 57;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 57;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 57;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 57;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 57;
UPDATE delhiid SET ac_name_14 = 'Laxmi Nagar' WHERE ac_id_09 = 58;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 58;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 58;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 58;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 58;
UPDATE delhiid SET ac_name_14 = 'Vishwas Nagar' WHERE ac_id_09 = 59;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 59;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 59;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 59;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 59;
UPDATE delhiid SET ac_name_14 = 'Krishna Nagar' WHERE ac_id_09 = 60;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 60;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 60;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 60;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 60;
UPDATE delhiid SET ac_name_14 = 'Gandhi Nagar' WHERE ac_id_09 = 61;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 61;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 61;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 61;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 61;
UPDATE delhiid SET ac_name_14 = 'Shahdara' WHERE ac_id_09 = 62;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 62;
UPDATE delhiid SET pc_id_09 = 3 WHERE ac_id_09 = 62;
UPDATE delhiid SET pc_name_09 = 'East Delhi' WHERE ac_id_09 = 62;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 62;
UPDATE delhiid SET ac_name_14 = 'Seema puri' WHERE ac_id_09 = 63;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 63;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 63;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 63;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 63;
UPDATE delhiid SET ac_name_14 = 'Rohtas Nagar' WHERE ac_id_09 = 64;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 64;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 64;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 64;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 64;
UPDATE delhiid SET ac_name_14 = 'Seelampur' WHERE ac_id_09 = 65;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 65;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 65;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 65;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 65;
UPDATE delhiid SET ac_name_14 = 'Ghonda' WHERE ac_id_09 = 66;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 66;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 66;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 66;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 66;
UPDATE delhiid SET ac_name_14 = 'Babarpur' WHERE ac_id_09 = 67;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 67;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 67;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 67;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 67;
UPDATE delhiid SET ac_name_14 = 'Gokalpur' WHERE ac_id_09 = 68;
UPDATE delhiid SET ac_reserved_14 = 'SC' WHERE ac_id_09 = 68;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 68;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 68;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 68;
UPDATE delhiid SET ac_name_14 = 'Mustafabad' WHERE ac_id_09 = 69;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 69;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 69;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 69;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 69;
UPDATE delhiid SET ac_name_14 = 'Karawal Nagar' WHERE ac_id_09 = 70;
UPDATE delhiid SET ac_reserved_14 = '' WHERE ac_id_09 = 70;
UPDATE delhiid SET pc_id_09 = 2 WHERE ac_id_09 = 70;
UPDATE delhiid SET pc_name_09 = 'North East Delhi' WHERE ac_id_09 = 70;
UPDATE delhiid SET pc_reserved_09 = '' WHERE ac_id_09 = 70;
COMMIT;
.mode csv
.headers on
.once delhiid/delhiid.csv
SELECT * FROM delhiid;
VACUUM;